# CMake generated Testfile for 
# Source directory: /data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico
# Build directory: /data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(z_data_struct_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_data_struct_test")
set_tests_properties(z_data_struct_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;728;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_channels_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_channels_test")
set_tests_properties(z_channels_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;729;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_collections_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_collections_test")
set_tests_properties(z_collections_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;730;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_endpoint_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_endpoint_test")
set_tests_properties(z_endpoint_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;731;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_iobuf_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_iobuf_test")
set_tests_properties(z_iobuf_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;732;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_msgcodec_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_msgcodec_test")
set_tests_properties(z_msgcodec_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;733;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_keyexpr_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_keyexpr_test")
set_tests_properties(z_keyexpr_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;734;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_api_null_drop_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_api_null_drop_test")
set_tests_properties(z_api_null_drop_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;735;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_api_double_drop_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_api_double_drop_test")
set_tests_properties(z_api_double_drop_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;736;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_bytes_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_bytes_test")
set_tests_properties(z_bytes_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;737;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_api_bytes_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_api_bytes_test")
set_tests_properties(z_api_bytes_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;738;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_api_encoding_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_api_encoding_test")
set_tests_properties(z_api_encoding_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;739;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_refcount_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_refcount_test")
set_tests_properties(z_refcount_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;740;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_lru_cache_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_lru_cache_test")
set_tests_properties(z_lru_cache_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;741;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_utils_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_utils_test")
set_tests_properties(z_utils_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;742;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_scheduler_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_scheduler_test")
set_tests_properties(z_scheduler_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;743;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_tls_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_tls_test")
set_tests_properties(z_tls_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;744;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_tls_config_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_tls_config_test")
set_tests_properties(z_tls_config_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;745;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_condvar_wait_until_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_condvar_wait_until_test")
set_tests_properties(z_condvar_wait_until_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;746;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_sync_group_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_sync_group_test")
set_tests_properties(z_sync_group_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;747;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_cancellation_token_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_cancellation_token_test")
set_tests_properties(z_cancellation_token_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;748;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_local_loopback_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_local_loopback_test")
set_tests_properties(z_local_loopback_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;749;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
add_test(z_json_encoder_test "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/build_default/tests/z_json_encoder_test")
set_tests_properties(z_json_encoder_test PROPERTIES  _BACKTRACE_TRIPLES "/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;750;add_test;/data/home/skynet/zcolony/milyin-zenoh-zbobr/workspaces/task#49/zenoh-pico/CMakeLists.txt;0;")
subdirs("examples")
