#!/usr/bin/env python3
"""
Patch ti_drivers_config.c generated by SysConfig for AM64x IPC-only builds.

When SysConfig generates the IPC driver init without memory_configurator,
the VRING offset macros are empty, producing invalid C like:

    rpmsgParams.vringTxBaseAddr[CSL_CORE_ID_R5FSS0_1] = (uintptr_t)(&gIpcSharedMem[]);

This script replaces those invalid expressions with (uintptr_t)0U.  This is
correct for a Linux-IPC-only build: R5F-to-R5F VRING addresses are unused when
no other RTOS cores participate in IPC.

Usage:
    python3 patch_ti_ipc_config.py <path/to/ti_drivers_config.c>
"""

import re
import sys


def patch(path: str) -> None:
    with open(path, encoding="utf-8") as fh:
        text = fh.read()

    # Fix empty subscript: (uintptr_t)(&gIpcSharedMem[])  ->  (uintptr_t)0U
    patched, n = re.subn(
        r"\(uintptr_t\)\(&gIpcSharedMem\[\]\)",
        "(uintptr_t)0U",
        text,
    )

    if n == 0:
        print(f"[patch_ti_ipc_config] {path}: nothing to patch")
        return

    with open(path, "w", encoding="utf-8") as fh:
        fh.write(patched)

    print(f"[patch_ti_ipc_config] {path}: replaced {n} empty gIpcSharedMem[] subscript(s)")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <ti_drivers_config.c>", file=sys.stderr)
        sys.exit(1)
    patch(sys.argv[1])
