CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_UDP=y
CONFIG_NET_DHCPV4=y
CONFIG_NET_CONFIG_SETTINGS=y
CONFIG_NET_CONFIG_NEED_IPV4=y

# Zenoh-Pico sizes its thread stacks after the main stack
CONFIG_MAIN_STACK_SIZE=4096

CONFIG_ZENOH_PICO=y
