/*
 * Copyright (c) 2026 ZettaScale Technology
 * Copyright (c) 2026 T3 Foundation Gemstone Project (www.t3gemstone.org)
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
 *
 * CPSW Enet + lwIP network initialisation for TI AM67A Cortex-R5F.
 *
 * Depends on:
 *   - FreeRTOS (for semaphores and task timing)
 *   - lwIP tcpip_thread API (tcpip_init, dhcp_start, netif_*)
 *   - TI MCU+ SDK SysConfig-generated files:
 *       ti_enet_lwipif.h / ti_enet_lwipif.c  (LwipifEnetApp_* API)
 *       ti_enet_config.h                      (ENET_SYSCFG_* constants)
 *
 * These SysConfig files must be generated by TI SysConfig for your board
 * and placed in examples/ti_am67a/syscfg/ before building. See README.md.
 */

#include "zenoh_net_init.h"

#include <string.h>

/* FreeRTOS */
#include "FreeRTOS.h"
#include "semphr.h"

/* lwIP core */
#include "lwip/dhcp.h"
#include "lwip/err.h"
#include "lwip/inet.h"
#include "lwip/netif.h"
#include "lwip/sys.h"
#include "lwip/tcpip.h"

/* TI DPL logging */
#include <kernel/dpl/DebugP.h>

/* SysConfig-generated: LwipifEnetApp_Handle, LwipifEnetApp_getHandle(),
 * LwipifEnetApp_netifOpen(), LwipifEnetApp_netifClose(),
 * LwipifEnetApp_startSchedule() */
#include "ti_enet_lwipif.h"

/* ---- Module state --------------------------------------------------------- */
static LwipifEnetApp_Handle s_hLwipApp;
static struct netif        *s_pNetif;
static struct dhcp          s_dhcp;  /* static DHCP struct — no heap needed */

/* Semaphores stored in static buffers (configSUPPORT_STATIC_ALLOCATION=1) */
static SemaphoreHandle_t s_tcpip_done_sem;
static StaticSemaphore_t s_tcpip_done_sem_buf;
static SemaphoreHandle_t s_dhcp_done_sem;
static StaticSemaphore_t s_dhcp_done_sem_buf;

/* Shared error code written by the tcpip_init callback, read by zenoh_net_init */
static volatile int s_setup_result;

/* ---- Internal callbacks --------------------------------------------------- */

/* Forward declaration — defined below */
static void _netif_status_cb(struct netif *netif);

/* Called by lwIP tcpip_thread after it is fully initialised.
 * Runs IN the tcpip_thread context — safe to call LwipifEnetApp_* here. */
static void _tcpip_init_done_cb(void *arg) {
    (void)arg;
    ip4_addr_t zero;
    ip4_addr_set_zero(&zero);

    /* Open the CPSW enet network interface */
    s_hLwipApp = LwipifEnetApp_getHandle();
    s_pNetif   = LwipifEnetApp_netifOpen(s_hLwipApp, ZENOH_NET_NETIF_IDX,
                                         &zero, &zero, &zero);
    if (s_pNetif == NULL) {
        DebugP_log("[zenoh_net] LwipifEnetApp_netifOpen failed\r\n");
        s_setup_result = ZENOH_NET_ERR_ENET;
        xSemaphoreGive(s_tcpip_done_sem);
        return;
    }

#if defined(ZENOH_NET_STATIC_IP)
    /* Static IP — assign address directly and bring the interface up */
    ip4_addr_t ipaddr, netmask, gw;
    ip4addr_aton(ZENOH_NET_STATIC_IP,   &ipaddr);
    ip4addr_aton(ZENOH_NET_STATIC_MASK, &netmask);
    ip4addr_aton(ZENOH_NET_STATIC_GW,   &gw);
    netif_set_addr(s_pNetif, &ipaddr, &netmask, &gw);
    netif_set_up(s_pNetif);
    DebugP_log("[zenoh_net] Static IP: %s\r\n", ip4addr_ntoa(netif_ip4_addr(s_pNetif)));
#else
    /* DHCP — the status callback signals s_dhcp_done_sem on IP assignment */
    netif_set_status_callback(s_pNetif, _netif_status_cb);
    netif_set_up(s_pNetif);
    dhcp_set_struct(s_pNetif, &s_dhcp);
    err_t err = dhcp_start(s_pNetif);
    if (err != ERR_OK) {
        DebugP_log("[zenoh_net] dhcp_start failed (%d)\r\n", (int)err);
        s_setup_result = ZENOH_NET_ERR_DHCP;
        xSemaphoreGive(s_tcpip_done_sem);
        return;
    }
#endif /* ZENOH_NET_STATIC_IP */

    /* Start the Enet Rx/Tx polling scheduler task */
    LwipifEnetApp_startSchedule(s_hLwipApp, s_pNetif);

    s_setup_result = ZENOH_NET_OK;
    xSemaphoreGive(s_tcpip_done_sem);
}

/* Status callback — called from tcpip_thread whenever the netif status changes.
 * We give s_dhcp_done_sem once a non-zero IP is assigned. */
static void _netif_status_cb(struct netif *netif) {
    if (netif_is_up(netif) && !ip4_addr_isany(netif_ip4_addr(netif))) {
        DebugP_log("[zenoh_net] IP acquired: %s\r\n",
                   ip4addr_ntoa(netif_ip4_addr(netif)));
        /* Only signal once (idempotent for repeated callbacks) */
        xSemaphoreGive(s_dhcp_done_sem);
    }
}

/* ---- Public API ----------------------------------------------------------- */

int zenoh_net_init(void) {
    s_setup_result = ZENOH_NET_OK;

    /* Semaphore: signals when tcpip_thread is ready and netif is opened */
    s_tcpip_done_sem = xSemaphoreCreateBinaryStatic(&s_tcpip_done_sem_buf);

#if !defined(ZENOH_NET_STATIC_IP)
    /* Semaphore: signals when DHCP assigns an IP */
    s_dhcp_done_sem = xSemaphoreCreateBinaryStatic(&s_dhcp_done_sem_buf);
    /* Register the status callback before tcpip_init so it is in place
     * when DHCP eventually fires — the callback is registered inside
     * _tcpip_init_done_cb, which runs in the tcpip_thread context. */
#endif

    /* Start lwIP tcpip_thread; _tcpip_init_done_cb runs inside that thread */
    tcpip_init(_tcpip_init_done_cb, NULL);

    /* Wait for netif open + DHCP start (or static IP assignment) to complete */
    xSemaphoreTake(s_tcpip_done_sem, portMAX_DELAY);

    if (s_setup_result != ZENOH_NET_OK) {
        return s_setup_result;
    }

#if !defined(ZENOH_NET_STATIC_IP)
    /* Wait for DHCP to acquire an IP address */
    TickType_t timeout_ticks = pdMS_TO_TICKS(ZENOH_NET_DHCP_TIMEOUT_MS);
    if (xSemaphoreTake(s_dhcp_done_sem, timeout_ticks) != pdTRUE) {
        DebugP_log("[zenoh_net] DHCP timeout after %u ms\r\n",
                   (unsigned)ZENOH_NET_DHCP_TIMEOUT_MS);
        return ZENOH_NET_ERR_TIMEOUT;
    }
#endif

    return ZENOH_NET_OK;
}

void zenoh_net_deinit(void) {
    if (s_pNetif != NULL) {
        sys_lock_tcpip_core();
        LwipifEnetApp_netifClose(s_hLwipApp, ZENOH_NET_NETIF_IDX);
        sys_unlock_tcpip_core();
        s_pNetif = NULL;
    }
}

int zenoh_net_ip_str(char *buf, size_t buflen) {
    if ((s_pNetif == NULL) || (buf == NULL)) {
        return -1;
    }
    const char *ip = ip4addr_ntoa(netif_ip4_addr(s_pNetif));
    size_t len = strlen(ip);
    if (len >= buflen) {
        return -1;
    }
    memcpy(buf, ip, len + 1U);
    return 0;
}
