zp_platform_set_system_layer(arduino_esp32)
zp_platform_add_sources("${PROJECT_SOURCE_DIR}/src/link/backend/stream/bt_arduino_esp32.cpp")
zp_platform_set_network(arduino_esp32)
set(CHECK_THREADS OFF)
zp_platform_set_tcp_backend(tcp_esp32)
zp_platform_set_udp_backend(esp32)
zp_platform_set_serial_backend(uart_arduino_esp32)
