set(ZP_PLATFORM_SYSTEM_LAYER flipper)
set(ZP_PLATFORM_SYSTEM_SOURCE_FILES
    "${PROJECT_SOURCE_DIR}/src/system/flipper/system.c")
set(ZP_PLATFORM_SYSTEM_COMPILE_DEFINITIONS ZENOH_FLIPPER)
set(ZP_PLATFORM_NETWORK flipper)
set(ZP_PLATFORM_NETWORK_SOURCE_FILES
    "${PROJECT_SOURCE_DIR}/src/system/flipper/network.c")
set(CHECK_THREADS OFF)
set(ZP_PLATFORM_SERIAL_SOURCE_FILES
    "${PROJECT_SOURCE_DIR}/src/link/backend/serial/uart_flipper.c")
