zp_platform_add_definition(ZENOH_FREERTOS_PLUS_TCP)
zp_platform_glob_sources("${PROJECT_SOURCE_DIR}/src/system/freertos/freertos_plus_tcp/*.c")
zp_platform_add_sources("${PROJECT_SOURCE_DIR}/src/system/freertos/system.c")
zp_platform_set_stream_backend(tcp_freertos_plus_tcp)
zp_platform_set_datagram_backend(udp_freertos_plus_tcp)
