function(zp_register_backend type)
  set(oneValueArgs NAME SYMBOL)
  set(multiValueArgs SOURCES INCLUDE_DIRS)
  cmake_parse_arguments(ARG "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  if(ARG_NAME STREQUAL "")
    message(FATAL_ERROR "zp_register_backend(${type} ...) requires NAME")
  endif()
  if(ARG_SYMBOL STREQUAL "")
    message(FATAL_ERROR "zp_register_backend(${type} ...) requires SYMBOL")
  endif()

  string(TOUPPER "${type}" _zp_backend_type)
  set_property(GLOBAL PROPERTY "ZP_${_zp_backend_type}_BACKEND_SYMBOL_${ARG_NAME}" "${ARG_SYMBOL}")
  set_property(GLOBAL PROPERTY "ZP_${_zp_backend_type}_BACKEND_SOURCES_${ARG_NAME}" "${ARG_SOURCES}")
  set_property(GLOBAL PROPERTY "ZP_${_zp_backend_type}_BACKEND_INCLUDE_DIRS_${ARG_NAME}" "${ARG_INCLUDE_DIRS}")
endfunction()

function(zp_get_backend_search_dirs type out_var)
  if(type STREQUAL "stream")
    set(${out_var} "${ZP_STREAM_BACKEND_DIRS}" PARENT_SCOPE)
  elseif(type STREQUAL "datagram")
    set(${out_var} "${ZP_DATAGRAM_BACKEND_DIRS}" PARENT_SCOPE)
  elseif(type STREQUAL "rawio")
    set(${out_var} "${ZP_RAWIO_BACKEND_DIRS}" PARENT_SCOPE)
  else()
    message(FATAL_ERROR "Unknown backend type: ${type}")
  endif()
endfunction()

function(zp_load_backend_descriptor type name)
  if(name STREQUAL "")
    return()
  endif()

  string(TOUPPER "${type}" _zp_backend_type)
  get_property(_zp_descriptor_loaded GLOBAL PROPERTY "ZP_${_zp_backend_type}_BACKEND_DESCRIPTOR_LOADED_${name}")
  if(_zp_descriptor_loaded)
    return()
  endif()

  zp_get_backend_search_dirs("${type}" _zp_backend_dirs)
  foreach(_zp_backend_dir IN LISTS _zp_backend_dirs)
    if(EXISTS "${_zp_backend_dir}/${name}.cmake")
      set_property(GLOBAL PROPERTY "ZP_${_zp_backend_type}_BACKEND_DESCRIPTOR_LOADED_${name}" TRUE)
      include("${_zp_backend_dir}/${name}.cmake")
      return()
    endif()
  endforeach()
endfunction()

function(zp_resolve_backend type name out_symbol out_sources out_include_dirs)
  if(name STREQUAL "")
    set(${out_symbol} "" PARENT_SCOPE)
    set(${out_sources} "" PARENT_SCOPE)
    set(${out_include_dirs} "" PARENT_SCOPE)
    return()
  endif()

  string(TOUPPER "${type}" _zp_backend_type)
  set(_zp_backend_symbol "")
  get_property(_zp_backend_symbol_set GLOBAL PROPERTY "ZP_${_zp_backend_type}_BACKEND_SYMBOL_${name}" SET)
  if(_zp_backend_symbol_set)
    get_property(_zp_backend_symbol GLOBAL PROPERTY "ZP_${_zp_backend_type}_BACKEND_SYMBOL_${name}")
  else()
    zp_load_backend_descriptor("${type}" "${name}")
    get_property(_zp_backend_symbol_set GLOBAL PROPERTY "ZP_${_zp_backend_type}_BACKEND_SYMBOL_${name}" SET)
    if(_zp_backend_symbol_set)
      get_property(_zp_backend_symbol GLOBAL PROPERTY "ZP_${_zp_backend_type}_BACKEND_SYMBOL_${name}")
    endif()
  endif()
  if("${_zp_backend_symbol}" STREQUAL "")
    zp_get_backend_search_dirs("${type}" _zp_backend_dirs)
    string(REPLACE ";" ", " _zp_backend_dirs_text "${_zp_backend_dirs}")
    message(FATAL_ERROR "Unknown ${type} backend: ${name}. Searched in: ${_zp_backend_dirs_text}")
  endif()

  get_property(_zp_backend_sources GLOBAL PROPERTY "ZP_${_zp_backend_type}_BACKEND_SOURCES_${name}")
  get_property(_zp_backend_include_dirs GLOBAL PROPERTY "ZP_${_zp_backend_type}_BACKEND_INCLUDE_DIRS_${name}")

  set(${out_symbol} "${_zp_backend_symbol}" PARENT_SCOPE)
  set(${out_sources} "${_zp_backend_sources}" PARENT_SCOPE)
  set(${out_include_dirs} "${_zp_backend_include_dirs}" PARENT_SCOPE)
endfunction()

macro(zp_register_stream_backend)
  zp_register_backend(stream ${ARGV})
endmacro()

macro(zp_register_datagram_backend)
  zp_register_backend(datagram ${ARGV})
endmacro()

macro(zp_register_rawio_backend)
  zp_register_backend(rawio ${ARGV})
endmacro()

macro(zp_resolve_stream_backend name out_symbol out_sources out_include_dirs)
  zp_resolve_backend(stream "${name}" ${out_symbol} ${out_sources} ${out_include_dirs})
endmacro()

macro(zp_resolve_datagram_backend name out_symbol out_sources out_include_dirs)
  zp_resolve_backend(datagram "${name}" ${out_symbol} ${out_sources} ${out_include_dirs})
endmacro()

macro(zp_resolve_rawio_backend name out_symbol out_sources out_include_dirs)
  zp_resolve_backend(rawio "${name}" ${out_symbol} ${out_sources} ${out_include_dirs})
endmacro()

macro(zp_add_stream_backend_dir value)
  list(APPEND ZP_STREAM_BACKEND_DIRS "${value}")
endmacro()

macro(zp_add_datagram_backend_dir value)
  list(APPEND ZP_DATAGRAM_BACKEND_DIRS "${value}")
endmacro()

macro(zp_add_rawio_backend_dir value)
  list(APPEND ZP_RAWIO_BACKEND_DIRS "${value}")
endmacro()

macro(zp_platform_set_stream_backend value)
  set(ZP_PLATFORM_DEFAULT_STREAM_BACKEND "${value}")
endmacro()

macro(zp_platform_set_datagram_backend value)
  set(ZP_PLATFORM_DEFAULT_DATAGRAM_BACKEND "${value}")
endmacro()

macro(zp_platform_set_rawio_backend value)
  set(ZP_PLATFORM_DEFAULT_RAWIO_BACKEND "${value}")
endmacro()

set(ZP_STREAM_BACKEND_DIRS "${CMAKE_CURRENT_LIST_DIR}/backends/stream")
set(ZP_DATAGRAM_BACKEND_DIRS "${CMAKE_CURRENT_LIST_DIR}/backends/datagram")
set(ZP_RAWIO_BACKEND_DIRS "${CMAKE_CURRENT_LIST_DIR}/backends/rawio")
