function(zp_register_network)
  set(oneValueArgs NAME SOCKET_OPS_SYMBOL SOCKET_COMPONENT TARGET)
  set(multiValueArgs SOURCES INCLUDE_DIRS LINK_LIBRARIES)
  cmake_parse_arguments(ARG "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  if("${ARG_NAME}" STREQUAL "")
    message(FATAL_ERROR "zp_register_network(...) requires NAME")
  endif()

  string(MAKE_C_IDENTIFIER "${ARG_NAME}" _zp_network_target_id)
  set(_zp_network_backing_target "zp_network_${_zp_network_target_id}")
  if("${ARG_TARGET}" STREQUAL "")
    zp_make_contract_target_name("network" "${ARG_NAME}" _zp_network_target)
  else()
    set(_zp_network_target "${ARG_TARGET}")
  endif()

  zp_ensure_interface_contract_target("${_zp_network_target}" "${_zp_network_backing_target}"
                                      _zp_network_actual_target)

  if(NOT "${ARG_SOURCES}" STREQUAL "")
    target_sources("${_zp_network_actual_target}" INTERFACE ${ARG_SOURCES})
  endif()
  if(NOT "${ARG_INCLUDE_DIRS}" STREQUAL "")
    target_include_directories("${_zp_network_actual_target}" INTERFACE ${ARG_INCLUDE_DIRS})
  endif()
  if(NOT "${ARG_LINK_LIBRARIES}" STREQUAL "")
    target_link_libraries("${_zp_network_actual_target}" INTERFACE ${ARG_LINK_LIBRARIES})
  endif()

  set_property(GLOBAL PROPERTY "ZP_NETWORK_TARGET_${ARG_NAME}" "${_zp_network_target}")
  set_property(TARGET "${_zp_network_actual_target}" PROPERTY
               ZP_NETWORK_SOCKET_OPS_SYMBOL "${ARG_SOCKET_OPS_SYMBOL}")
  set_property(TARGET "${_zp_network_actual_target}" PROPERTY
               ZP_NETWORK_SOCKET_COMPONENT "${ARG_SOCKET_COMPONENT}")
endfunction()

function(zp_load_network_descriptor name)
  if(name STREQUAL "")
    return()
  endif()

  get_property(_zp_descriptor_loaded GLOBAL PROPERTY "ZP_NETWORK_DESCRIPTOR_LOADED_${name}")
  if(_zp_descriptor_loaded)
    return()
  endif()

  foreach(_zp_network_dir IN LISTS ZP_NETWORK_DIRS)
    if(EXISTS "${_zp_network_dir}/${name}.cmake")
      set_property(GLOBAL PROPERTY "ZP_NETWORK_DESCRIPTOR_LOADED_${name}" TRUE)
      include("${_zp_network_dir}/${name}.cmake")
      return()
    endif()
  endforeach()
endfunction()

function(zp_resolve_network name out_socket_ops_symbol out_socket_component out_target)
  if(name STREQUAL "")
    set(${out_socket_ops_symbol} "" PARENT_SCOPE)
    set(${out_socket_component} "" PARENT_SCOPE)
    set(${out_target} "" PARENT_SCOPE)
    return()
  endif()

  zp_make_contract_target_name("network" "${name}" _zp_network_target)
  if(NOT TARGET "${_zp_network_target}")
    zp_load_network_descriptor("${name}")
  endif()
  if(NOT TARGET "${_zp_network_target}")
    get_property(_zp_network_target GLOBAL PROPERTY "ZP_NETWORK_TARGET_${name}")
  endif()
  if(_zp_network_target STREQUAL "" OR NOT TARGET "${_zp_network_target}")
    string(REPLACE ";" ", " _zp_network_dirs_text "${ZP_NETWORK_DIRS}")
    message(FATAL_ERROR "Unknown network: ${name}. Searched in: ${_zp_network_dirs_text}")
  endif()
  if(_zp_network_target STREQUAL "" OR NOT TARGET "${_zp_network_target}")
    message(FATAL_ERROR "Network ${name} did not register a valid CMake target")
  endif()

  get_target_property_if_set(_zp_network_socket_ops_symbol "${_zp_network_target}" ZP_NETWORK_SOCKET_OPS_SYMBOL)
  get_target_property_if_set(_zp_network_socket_component "${_zp_network_target}" ZP_NETWORK_SOCKET_COMPONENT)
  if(NOT DEFINED _zp_network_socket_ops_symbol)
    set(_zp_network_socket_ops_symbol "")
  endif()
  if(NOT DEFINED _zp_network_socket_component)
    set(_zp_network_socket_component "")
  endif()
  set(${out_socket_ops_symbol} "${_zp_network_socket_ops_symbol}" PARENT_SCOPE)
  set(${out_socket_component} "${_zp_network_socket_component}" PARENT_SCOPE)
  set(${out_target} "${_zp_network_target}" PARENT_SCOPE)
endfunction()

macro(zp_platform_set_network value)
  set(ZP_PLATFORM_NETWORK "${value}")
endmacro()

set(ZP_NETWORK_DIRS "${CMAKE_CURRENT_LIST_DIR}/network")
