function(zp_load_network_descriptor name out_var)
  set(_zp_descriptor_file "")
  if(NOT name STREQUAL "")
    foreach(_zp_network_dir IN LISTS ZP_NETWORK_DIRS)
      if(EXISTS "${_zp_network_dir}/${name}.cmake")
        set(_zp_descriptor_file "${_zp_network_dir}/${name}.cmake")
        break()
      endif()
    endforeach()
  endif()
  set(${out_var} "${_zp_descriptor_file}" PARENT_SCOPE)
endfunction()

function(zp_resolve_network name)
  set(_zp_network_source_files "")
  set(_zp_network_include_dirs "")
  set(_zp_network_compile_definitions "")
  set(_zp_network_compile_options "")
  set(_zp_network_link_libraries "")
  set(_zp_network_socket_component "")

  if(NOT name STREQUAL "")
    set(ZP_NETWORK_SOURCE_FILES "")
    set(ZP_NETWORK_INCLUDE_DIRS "")
    set(ZP_NETWORK_COMPILE_DEFINITIONS "")
    set(ZP_NETWORK_COMPILE_OPTIONS "")
    set(ZP_NETWORK_LINK_LIBRARIES "")
    set(ZP_NETWORK_SOCKET_COMPONENT "")

    zp_load_network_descriptor("${name}" _zp_network_descriptor_file)
    if("${_zp_network_descriptor_file}" STREQUAL "")
      string(REPLACE ";" ", " _zp_network_dirs_text "${ZP_NETWORK_DIRS}")
      message(FATAL_ERROR "Unknown network: ${name}. Searched in: ${_zp_network_dirs_text}")
    endif()

    include("${_zp_network_descriptor_file}")
    set(_zp_network_source_files "${ZP_NETWORK_SOURCE_FILES}")
    set(_zp_network_include_dirs "${ZP_NETWORK_INCLUDE_DIRS}")
    set(_zp_network_compile_definitions "${ZP_NETWORK_COMPILE_DEFINITIONS}")
    set(_zp_network_compile_options "${ZP_NETWORK_COMPILE_OPTIONS}")
    set(_zp_network_link_libraries "${ZP_NETWORK_LINK_LIBRARIES}")
    set(_zp_network_socket_component "${ZP_NETWORK_SOCKET_COMPONENT}")
  endif()

  set(ZP_NETWORK_SOURCE_FILES "${_zp_network_source_files}" PARENT_SCOPE)
  set(ZP_NETWORK_INCLUDE_DIRS "${_zp_network_include_dirs}" PARENT_SCOPE)
  set(ZP_NETWORK_COMPILE_DEFINITIONS "${_zp_network_compile_definitions}" PARENT_SCOPE)
  set(ZP_NETWORK_COMPILE_OPTIONS "${_zp_network_compile_options}" PARENT_SCOPE)
  set(ZP_NETWORK_LINK_LIBRARIES "${_zp_network_link_libraries}" PARENT_SCOPE)
  set(ZP_NETWORK_SOCKET_COMPONENT "${_zp_network_socket_component}" PARENT_SCOPE)
endfunction()

macro(zp_platform_set_network value)
  set(ZP_PLATFORM_NETWORK "${value}")
endmacro()

set(ZP_NETWORK_DIRS "${CMAKE_CURRENT_LIST_DIR}/network")
