function(zp_detect_default_platform out_var)
  if(CMAKE_SYSTEM_NAME MATCHES "Linux")
    set(${out_var} "linux" PARENT_SCOPE)
  elseif(POSIX_COMPATIBLE)
    set(${out_var} "posix_compatible" PARENT_SCOPE)
  elseif(CMAKE_SYSTEM_NAME MATCHES "BSD")
    set(${out_var} "bsd" PARENT_SCOPE)
  elseif(CMAKE_SYSTEM_NAME MATCHES "Darwin")
    set(${out_var} "macos" PARENT_SCOPE)
  elseif(CMAKE_SYSTEM_NAME MATCHES "Emscripten")
    set(${out_var} "emscripten" PARENT_SCOPE)
  elseif(CMAKE_SYSTEM_NAME MATCHES "Windows")
    set(${out_var} "windows" PARENT_SCOPE)
  elseif(CMAKE_SYSTEM_NAME MATCHES "Generic")
    message(FATAL_ERROR "A Generic build requires an explicit ZP_PLATFORM (for example zephyr, freertos_plus_tcp, or freertos_lwip)")
  elseif(CMAKE_SYSTEM_NAME MATCHES "PICO")
    set(${out_var} "rpi_pico" PARENT_SCOPE)
  else()
    message(FATAL_ERROR "zenoh-pico is not yet available on ${CMAKE_SYSTEM_NAME} platform")
  endif()
endfunction()

macro(zp_add_platform_dir value)
  list(APPEND ZP_PLATFORM_DIRS "${value}")
endmacro()

macro(zp_load_platform_profile profile_name)
  set(ZP_PLATFORM_PROFILE_FILE "")
  set(ZP_PLATFORM_COMPILE_DEFINITIONS "")
  set(ZP_PLATFORM_SOURCE_GLOBS "")
  set(ZP_PLATFORM_SOURCE_FILES "")
  set(ZP_PLATFORM_INCLUDE_DIRS "")
  set(ZP_PLATFORM_COMPILE_OPTIONS "")
  set(ZP_PLATFORM_LINK_LIBRARIES "")
  set(ZP_PLATFORM_SYSTEM_LAYER "")
  set(ZP_PLATFORM_SYSTEM_PLATFORM_HEADER "")
  set(CHECK_THREADS "ON")

  foreach(_zp_platform_dir IN LISTS ZP_PLATFORM_DIRS)
    if(EXISTS "${_zp_platform_dir}/${profile_name}.cmake")
      set(ZP_PLATFORM_PROFILE_FILE "${_zp_platform_dir}/${profile_name}.cmake")
      break()
    endif()
  endforeach()

  if(ZP_PLATFORM_PROFILE_FILE STREQUAL "")
    message(FATAL_ERROR "Unknown platform profile: ${profile_name}")
  endif()

  include("${ZP_PLATFORM_PROFILE_FILE}")
endmacro()
