function(zp_detect_default_platform out_var)
  if(CMAKE_SYSTEM_NAME MATCHES "Linux")
    set(${out_var} "linux" PARENT_SCOPE)
  elseif(POSIX_COMPATIBLE)
    set(${out_var} "posix_compatible" PARENT_SCOPE)
  elseif(CMAKE_SYSTEM_NAME MATCHES "BSD")
    set(${out_var} "bsd" PARENT_SCOPE)
  elseif(CMAKE_SYSTEM_NAME MATCHES "Darwin")
    set(${out_var} "macos" PARENT_SCOPE)
  elseif(CMAKE_SYSTEM_NAME MATCHES "Emscripten")
    set(${out_var} "emscripten" PARENT_SCOPE)
  elseif(CMAKE_SYSTEM_NAME MATCHES "Windows")
    set(${out_var} "windows" PARENT_SCOPE)
  elseif(CMAKE_SYSTEM_NAME MATCHES "Generic")
    message(FATAL_ERROR "A Generic build requires an explicit ZP_PLATFORM (for example zephyr, freertos_plus_tcp, or freertos_lwip)")
  elseif(CMAKE_SYSTEM_NAME MATCHES "PICO")
    set(${out_var} "rpi_pico" PARENT_SCOPE)
  else()
    message(FATAL_ERROR "zenoh-pico is not yet available on ${CMAKE_SYSTEM_NAME} platform")
  endif()
endfunction()

macro(zp_add_platform_dir value)
  list(APPEND ZP_PLATFORM_DIRS "${value}")
endmacro()

function(zp_register_system_layer_profile)
  set(oneValueArgs SYSTEM_LAYER PROFILE)
  cmake_parse_arguments(ARG "" "${oneValueArgs}" "" ${ARGN})

  if(ARG_SYSTEM_LAYER STREQUAL "")
    message(FATAL_ERROR "zp_register_system_layer_profile(...) requires SYSTEM_LAYER")
  endif()
  if(ARG_PROFILE STREQUAL "")
    message(FATAL_ERROR "zp_register_system_layer_profile(...) requires PROFILE")
  endif()

  set_property(GLOBAL PROPERTY "ZP_SYSTEM_LAYER_PROFILE_${ARG_SYSTEM_LAYER}" "${ARG_PROFILE}")
  set_property(GLOBAL PROPERTY "ZP_PROFILE_SYSTEM_LAYER_${ARG_PROFILE}" "${ARG_SYSTEM_LAYER}")
endfunction()

macro(zp_platform_add_definition value)
  list(APPEND ZP_PLATFORM_COMPILE_DEFINITIONS "${value}")
endmacro()

macro(zp_platform_set_system_layer value)
  set(ZP_PLATFORM_SYSTEM_LAYER "${value}")
endmacro()

macro(zp_platform_glob_sources)
  list(APPEND ZP_PLATFORM_SOURCE_GLOBS ${ARGV})
endmacro()

macro(zp_platform_add_sources)
  list(APPEND ZP_PLATFORM_SOURCE_FILES ${ARGV})
endmacro()

macro(zp_platform_add_include_dirs)
  list(APPEND ZP_PLATFORM_INCLUDE_DIRS ${ARGV})
endmacro()

macro(zp_load_platform_profile profile_name)
  set(ZP_PLATFORM_PROFILE_FILE "")
  set(ZP_PLATFORM_COMPILE_DEFINITIONS "")
  set(ZP_PLATFORM_SOURCE_GLOBS "")
  set(ZP_PLATFORM_SOURCE_FILES "")
  set(ZP_PLATFORM_INCLUDE_DIRS "")
  set(ZP_PLATFORM_SYSTEM_LAYER "")
  set(ZP_PLATFORM_NETWORK "")
  set(CHECK_THREADS "ON")
  set(ZP_PLATFORM_DEFAULT_TCP_BACKEND "")
  set(ZP_PLATFORM_DEFAULT_UDP_BACKEND "")
  set(ZP_PLATFORM_DEFAULT_SERIAL_BACKEND "")

  foreach(_zp_platform_dir IN LISTS ZP_PLATFORM_DIRS)
    if(EXISTS "${_zp_platform_dir}/${profile_name}.cmake")
      set(ZP_PLATFORM_PROFILE_FILE "${_zp_platform_dir}/${profile_name}.cmake")
      break()
    endif()
  endforeach()

  if(ZP_PLATFORM_PROFILE_FILE STREQUAL "")
    message(FATAL_ERROR "Unknown platform profile: ${profile_name}")
  endif()

  include("${ZP_PLATFORM_PROFILE_FILE}")
endmacro()

function(zp_resolve_platform_profile_for_system_layer out_var system_layer_name)
  set(_zp_profile_name "")

  foreach(_zp_platform_dir IN LISTS ZP_PLATFORM_DIRS)
    if(EXISTS "${_zp_platform_dir}/${system_layer_name}.cmake")
      set(_zp_profile_name "${system_layer_name}")
      break()
    endif()
  endforeach()

  if(_zp_profile_name STREQUAL "")
    get_property(_zp_system_layer_profile_set GLOBAL PROPERTY "ZP_SYSTEM_LAYER_PROFILE_${system_layer_name}" SET)
    if(_zp_system_layer_profile_set)
      get_property(_zp_profile_name GLOBAL PROPERTY "ZP_SYSTEM_LAYER_PROFILE_${system_layer_name}")
    endif()
  endif()

  set(${out_var} "${_zp_profile_name}" PARENT_SCOPE)
endfunction()

zp_register_system_layer_profile(SYSTEM_LAYER arduino_opencr PROFILE opencr)
