function(zp_load_socket_component_descriptor name out_var)
  set(_zp_descriptor_file "")
  if(NOT name STREQUAL "")
    foreach(_zp_socket_component_dir IN LISTS ZP_SOCKET_COMPONENT_DIRS)
      if(EXISTS "${_zp_socket_component_dir}/${name}.cmake")
        set(_zp_descriptor_file "${_zp_socket_component_dir}/${name}.cmake")
        break()
      endif()
    endforeach()
  endif()
  set(${out_var} "${_zp_descriptor_file}" PARENT_SCOPE)
endfunction()

function(zp_resolve_socket_component name)
  set(_zp_socket_source_files "")
  set(_zp_socket_include_dirs "")
  set(_zp_socket_compile_definitions "")
  set(_zp_socket_compile_options "")
  set(_zp_socket_link_libraries "")

  if(NOT name STREQUAL "")
    set(ZP_SOCKET_COMPONENT_SOURCE_FILES "")
    set(ZP_SOCKET_COMPONENT_INCLUDE_DIRS "")
    set(ZP_SOCKET_COMPONENT_COMPILE_DEFINITIONS "")
    set(ZP_SOCKET_COMPONENT_COMPILE_OPTIONS "")
    set(ZP_SOCKET_COMPONENT_LINK_LIBRARIES "")

    zp_load_socket_component_descriptor("${name}" _zp_socket_descriptor_file)
    if("${_zp_socket_descriptor_file}" STREQUAL "")
      string(REPLACE ";" ", " _zp_socket_component_dirs_text "${ZP_SOCKET_COMPONENT_DIRS}")
      message(FATAL_ERROR
              "Unknown socket component: ${name}. Searched in: ${_zp_socket_component_dirs_text}")
    endif()

    include("${_zp_socket_descriptor_file}")
    set(_zp_socket_compile_definitions "${ZP_SOCKET_COMPONENT_COMPILE_DEFINITIONS}")
    set(_zp_socket_source_files "${ZP_SOCKET_COMPONENT_SOURCE_FILES}")
    set(_zp_socket_include_dirs "${ZP_SOCKET_COMPONENT_INCLUDE_DIRS}")
    set(_zp_socket_compile_options "${ZP_SOCKET_COMPONENT_COMPILE_OPTIONS}")
    set(_zp_socket_link_libraries "${ZP_SOCKET_COMPONENT_LINK_LIBRARIES}")
  endif()

  set(ZP_SOCKET_COMPONENT_SOURCE_FILES "${_zp_socket_source_files}" PARENT_SCOPE)
  set(ZP_SOCKET_COMPONENT_INCLUDE_DIRS "${_zp_socket_include_dirs}" PARENT_SCOPE)
  set(ZP_SOCKET_COMPONENT_COMPILE_DEFINITIONS "${_zp_socket_compile_definitions}" PARENT_SCOPE)
  set(ZP_SOCKET_COMPONENT_COMPILE_OPTIONS "${_zp_socket_compile_options}" PARENT_SCOPE)
  set(ZP_SOCKET_COMPONENT_LINK_LIBRARIES "${_zp_socket_link_libraries}" PARENT_SCOPE)
endfunction()

set(ZP_SOCKET_COMPONENT_DIRS "")
