function(zp_register_system_layer)
  set(oneValueArgs NAME TARGET)
  set(multiValueArgs SOURCES INCLUDE_DIRS LINK_LIBRARIES COMPILE_DEFINITIONS)
  cmake_parse_arguments(ARG "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  if("${ARG_NAME}" STREQUAL "")
    message(FATAL_ERROR "zp_register_system_layer(...) requires NAME")
  endif()

  string(MAKE_C_IDENTIFIER "${ARG_NAME}" _zp_system_layer_target_id)
  set(_zp_system_layer_backing_target "zp_system_layer_${_zp_system_layer_target_id}")
  if("${ARG_TARGET}" STREQUAL "")
    zp_make_contract_target_name("system" "${ARG_NAME}" _zp_system_layer_target)
  else()
    set(_zp_system_layer_target "${ARG_TARGET}")
  endif()

  zp_ensure_interface_contract_target("${_zp_system_layer_target}" "${_zp_system_layer_backing_target}"
                                      _zp_system_layer_actual_target)

  if(NOT "${ARG_SOURCES}" STREQUAL "")
    target_sources("${_zp_system_layer_actual_target}" INTERFACE ${ARG_SOURCES})
  endif()
  if(NOT "${ARG_INCLUDE_DIRS}" STREQUAL "")
    target_include_directories("${_zp_system_layer_actual_target}" INTERFACE ${ARG_INCLUDE_DIRS})
  endif()
  if(NOT "${ARG_LINK_LIBRARIES}" STREQUAL "")
    target_link_libraries("${_zp_system_layer_actual_target}" INTERFACE ${ARG_LINK_LIBRARIES})
  endif()
  if(NOT "${ARG_COMPILE_DEFINITIONS}" STREQUAL "")
    target_compile_definitions("${_zp_system_layer_actual_target}" INTERFACE ${ARG_COMPILE_DEFINITIONS})
  endif()

  set_property(GLOBAL PROPERTY "ZP_SYSTEM_LAYER_TARGET_${ARG_NAME}" "${_zp_system_layer_target}")
endfunction()

function(zp_load_system_layer_descriptor name)
  if(name STREQUAL "")
    return()
  endif()

  get_property(_zp_descriptor_loaded GLOBAL PROPERTY "ZP_SYSTEM_LAYER_DESCRIPTOR_LOADED_${name}")
  if(_zp_descriptor_loaded)
    return()
  endif()

  foreach(_zp_system_layer_dir IN LISTS ZP_SYSTEM_LAYER_DIRS)
    if(EXISTS "${_zp_system_layer_dir}/${name}.cmake")
      set_property(GLOBAL PROPERTY "ZP_SYSTEM_LAYER_DESCRIPTOR_LOADED_${name}" TRUE)
      include("${_zp_system_layer_dir}/${name}.cmake")
      return()
    endif()
  endforeach()
endfunction()

function(zp_resolve_system_layer name out_target)
  if(name STREQUAL "")
    set(${out_target} "" PARENT_SCOPE)
    return()
  endif()

  zp_make_contract_target_name("system" "${name}" _zp_system_layer_target)
  if(NOT TARGET "${_zp_system_layer_target}")
    zp_load_system_layer_descriptor("${name}")
  endif()
  if(NOT TARGET "${_zp_system_layer_target}")
    get_property(_zp_system_layer_target GLOBAL PROPERTY "ZP_SYSTEM_LAYER_TARGET_${name}")
  endif()
  if(_zp_system_layer_target STREQUAL "" OR NOT TARGET "${_zp_system_layer_target}")
    string(REPLACE ";" ", " _zp_system_layer_dirs_text "${ZP_SYSTEM_LAYER_DIRS}")
    message(FATAL_ERROR "Unknown system layer component: ${name}. Searched in: ${_zp_system_layer_dirs_text}")
  endif()

  set(${out_target} "${_zp_system_layer_target}" PARENT_SCOPE)
endfunction()

set(ZP_SYSTEM_LAYER_DIRS "${CMAKE_CURRENT_LIST_DIR}/system")
