#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
name: build-shared

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Compile debug
      run: make all
      env:
        BUILD_TYPE: Debug
        BUILD_SHARED_LIBS: ON
        BUILD_TESTING: ON
        BUILD_MULTICAST: ON
        BUILD_INTEGRATION: ON
        BUILD_TOOLS: ON
        ZENOH_DEBUG: 3

  crossbuilds:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Crosscompile debug
      run: make crossbuilds
      env:
        BUILD_TYPE: Debug
        BUILD_SHARED_LIBS: ON
        ZENOH_DEBUG: 3

  modular_build:
    name: Modular build on ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature_publication: [1, 0]
        feature_subscription: [1, 0]
        feature_queryable: [1, 0]
        feature_query: [1, 0]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run docker image
      run: docker run --name zenoh_router --init --net host -d eclipse/zenoh:master
      continue-on-error: true

    - name: Build project
      run: |
        make all
        ./build/tests/z_modular_test $Z_FEATURE_PUBLICATION $Z_FEATURE_SUBSCRIPTION $Z_FEATURE_QUERYABLE $Z_FEATURE_QUERY
      continue-on-error: true
      env:
        BUILD_TYPE: Debug
        ZENOH_DEBUG: 3
        Z_FEATURE_PUBLICATION: ${{ matrix.feature_publication }}
        Z_FEATURE_SUBSCRIPTION: ${{ matrix.feature_subscription }}
        Z_FEATURE_QUERYABLE: ${{ matrix.feature_queryable }}
        Z_FEATURE_QUERY: ${{ matrix.feature_query }}
    
    - name: Stop docker image
      run: |
        docker stop zenoh_router
        docker rm zenoh_router