#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
name: multicast

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "0 6 * * 1-5"

jobs:
  build:
    name: Build on macOS-latest
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Compile debug
        run: make all
        env:
          BUILD_TYPE: Debug
          BUILD_TESTING: OFF
          BUILD_MULTICAST: ON
          BUILD_INTEGRATION: OFF
          ZENOH_BRANCH: dev/1.0.0

      - name: Test debug
        run: make test
        env:
          ARGS: -V
